services:
  prograrr:
    build: .
    container_name: prograrr
    environment:
      - TZ=${TIMEZONE}
      - PORT=3000
      - PROGRARR_API_KEY=${PROGRARR_API_KEY}
      - JELLYSEERR_URL=${JELLYSEERR_URL}
      - JELLYSEERR_API_KEY=${JELLYSEERR_API_KEY}
      - SONARR_URL=${SONARR_URL}
      - SONARR_API_KEY=${SONARR_API_KEY}
      - RADARR_URL=${RADARR_URL}
      - RADARR_API_KEY=${RADARR_API_KEY}
      - QBITTORRENT_URL=${QBITTORRENT_URL}
      - QBITTORRENT_USERNAME=${QBITTORRENT_USERNAME}
      - QBITTORRENT_PASSWORD=${QBITTORRENT_PASSWORD}
      - SABNZBD_URL=${SABNZBD_URL}
      - SABNZBD_API_KEY=${SABNZBD_API_KEY}
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - media_repo_default

networks:
  media_repo_default:
    external: true